apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx-pod
    type: front-end
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008