---
username: root
password: "Mavaratchi1."
git_repo: "git@github.com:MurtadhaM/Ansible-Network-Automation.git"
source_dir: "/opt/backups/Ansible-Network-Automation/backups"
git_user: "MurtadhaM"
git_email: "mmarzou0@gmail.com"
git_dir: "/opt/backups/Ansible-Network-Automation/backups"
